version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    container_name: revitalize_backend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    volumes:
      - ./:/app

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    container_name: revitalize_frontend
    ports:
      - "8080:80"
    environment:
      - VITE_API_URL=http://localhost:3001
